### ISSUE TITLE
schema:check fails on add of new type

### ISSUE THREAD

**Issue by rockrep** [apollographql/apollo-cli#500]
apollo-cli 1.4.0
apollo-engine 1.1.2
apollo-server 1.3.6

Have been using schema:check and schema:publish.   Everything works when adding a new field to a type, but schema:check fails when adding any new type with the following error:

```
 ✖ Checking schema for changes
   → Cannot read property 'hasOwnProperty' of undefined
 ›   Error: Cannot read property 'hasOwnProperty' of undefined
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
```

**Comment by lsanwick** [comment]
I'm also seeing this issue, but I haven't been able to determine the exact situation that causes it yet.

**Comment by lsanwick** [comment]
I've verified that this seems to be happening on the addition of any new type to my schema, which obviously invalidates the whole `schema:check` process.  Is there any chance this can be looked at sooner rather than later?  The code that is failing appears to be in the engine itself, not in the open source CLI tool, or I would put up a PR to fix it.

**Comment by daniman** [comment]
@lsanwick @rockrep Thanks for filing the issue! We deployed a fix for this in the Engine registry yesterday. Can you try it again?

**Comment by rockrep** [comment]
@daniman yep!  works great.  thanks for the quick fix!
