### ISSUE TITLE
schema:download generates incompatible schema JSON

### ISSUE THREAD

**Issue by michaelbromley** [apollographql/apollo-cli#555]
- [x] has-reproduction

## Version
apollo v1.7.0

## Description
Running `apollo schema:download` generates JSON which omits the "__schema" root property. This seems to break with convention (e.g. [intellij GraphQL plugin](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/28), [graphql-js introspection tests](https://github.com/graphql/graphql-js/blob/36dc1492dc8a6917e5327ef5d98e6662e6e15825/src/__tests__/starWarsIntrospection-test.js), [relay-starter-kit](https://github.com/relayjs/relay-starter-kit/blob/d182c5d2301cc3596e2da8a2d20ea6dce50f5eef/data/schema.json), [spectrum](https://github.com/withspectrum/spectrum/blob/54d0a1d4c57f860269bd51f7539933492184cd61/shared/graphql/schema.json)).

I am using the intellij GraphQL plugin and it is unfortunately unable to read the output from apollo at the moment.

## Steps to reproduce

1. `npm install apollo` 
2. `npx apollo schema:download schema.json --endpoint=https://graphql-pokemon.now.sh`

## Expected

The schema.json file should have the root property "__schema"

## Actual

The"__schema" property is missing and instead it seems to have been unwrapped so that the root properties are "queryType", "mutationType", etc.

**Comment by jamesmbourne** [comment]
This schema format is also incompatible with [apollo-android](https://github.com/apollographql/apollo-android), which is still internally using the now-deprecated `apollo-codegen`.

Quick-and-dirty `sed` to wrap the existing file:
```
sed -i 's/.*/{"__schema":&}/' schema.json
```

**Comment by danilobuerger** [comment]
Changing this would also mean changing `codegen:generate` as this relies on the schema without `__schema`.

**Comment by jamesmbourne** [comment]
@danilobuerger I am currently using `codegen:generate` with TypeScript and it appears to have no issue parsing a schema with `__schema` as the root node, but I haven't tried this with any other languages supported by `generate`.

The https://github.com/graphql/graphql-js reference implementation used here makes reference to `__schema` in [introspectionQuery.js#L22](https://github.com/graphql/graphql-js/blob/926e4d80c558b107c49e9403e943086fa9b043a8/src/utilities/introspectionQuery.js#L22) so I think this shouldn't be too much of an issue.

I believe that it may in fact be the case that the root node should be `data`, with `__schema` as a child of that based upon this [schema.json](https://github.com/apollographql/apollo-cli/blob/6570f72b919927c38e31d368f5b97168ec201377/packages/common-test/fixtures/misc/schema.json#L2), although I can't find any kind of specification to confirm this.

**Comment by jamesmbourne** [comment]
I've resolved the issue discussed here in #562, although I've also noticed that `codegen:generate` also outputs a schema missing this nesting.

Is this something that should be included in the aforementioned PR?

**Comment by martijnwalraven** [comment]
@jamesmbourne I merged your PR and that seems like the right fix, but wondering what you mean by:
>>> I've also noticed that codegen:generate also outputs a schema missing this nesting when using the JSON output format

**Comment by jamesmbourne** [comment]
@martijnwalraven Thanks for getting that merged in!

I was referring to the `codegen:generate` when used with an output type of JSON   (see [generate.ts#L136](https://github.com/apollographql/apollo-cli/blob/6570f72b919927c38e31d368f5b97168ec201377/packages/apollo-cli/src/commands/codegen/generate.ts#L136) for the implementation and [here](https://github.com/apollographql/apollo-cli/blob/6570f72b919927c38e31d368f5b97168ec201377/packages/apollo-cli/src/commands/codegen/__tests__/generate.test.ts#L299) for the covering test case and the [snapshot](https://github.com/apollographql/apollo-cli/blob/6570f72b919927c38e31d368f5b97168ec201377/packages/apollo-cli/src/commands/codegen/__tests__/__snapshots__/generate.test.ts.snap#L97)), although I think this is behaving as expected by outputting `"operations"` as the root key, and doesn't require the `"data"/"__schema"` keys so that point can be ignored.

**Comment by dariuxmx** [comment]
Seems happens with iOS too using `apollo schema:download`.
