### ISSUE TITLE
Having issues with Graphql Fragments 

### ISSUE THREAD

**Issue by OGNeutron** [apollographql/apollo-cli#556]
```
export const MESSAGE_FRAGMENT = gql`
	fragment MessageFragment on Message {
		id
		parentId
		body
		author {
			username
			avatar_url {
				url
			}
		}
	}
`


export const SHOW_CHANNEL_QUERY = gql`
	query ShowChannelQuery($channelId: ID!) {
		showChannel(channelId: $channelId) {
			id
			name
			slug
			messages {
				...MessageFragment
			}
		}
	}
	${MESSAGE_FRAGMENT}
`

```

Works fine with querying, but when I try to generate types I get a error saying unknown fragment.

**Comment by evans** [comment]
Thanks for reporting the issue! Definitely need to get this solved. The issue here is that our current query extraction looks for the gql` and doesn't perform any string interpolation. We'll need to add that. My first thought is some AST magic. Do you have any ideas on tools to use for that sort of work?

**Comment by marcosfede** [comment]
@evans 

I'm still unable to use fragments on version `2.18.0`

`Unknown fragment "teamDraftInfo"`
`ToolError: Validation of GraphQL query document failed`

should this be working?
